### ISSUE TITLE
FODCircleView.java

### ISSUE THREAD

**Issue by se7ensde** [BlissRoms/platform_frameworks_base#11]
Breaks force fingerprint authentication feature not allowing fingerprint sensor to show up immediately after reboot like it should when force fingerprint authentication feature is turned. This commit is counter intuitive to that feature. I know it is the issue cause i reverted this commit locally and built and the issue is gone.

**Comment by se7ensde** [comment]
I'll just open it again and again again till you fix it. This is an actual
issue that effect more than one tile style.

**Comment by se7ensde** [comment]
Oh yeah my guacamole builds are light years ahead of anything you guys come
up with for 7 pro. Pyrtle left you. I know you already take care of
multiple devices. You want a real maintainer for guacamole that would be
me.

**Comment by ideaman924** [comment]
This conversation thread will be locked. Please leave our team members alone.
