### ISSUE TITLE
checkpublicapi-last-timestamp' failed

### ISSUE THREAD

**Issue by moonlightly** [BlissRoms/platform_frameworks_base#4]
Checking API: checkpublicapi-last
Checking API: checkpublicapi-current
Checking API: checksystemapi-last
Checking API: checksystemapi-current
APK certs list: /home/moonlight/bliss/out/target/product/shamu/obj/PACKAGING/apkcerts_intermediates/bliss_shamu-apkcerts-521993fcbe.txt
/home/moonlight/bliss/out/target/common/obj/PACKAGING/public_api.txt:1815: error 17: Field android.R.string.fingerprint_icon_content_description has changed value from 17039384 to 17039385

---

You have tried to change the API from what has been previously released in
an SDK.  Please fix the errors listed above.

---

build/core/tasks/apicheck.mk:46: recipe for target '/home/moonlight/bliss/out/target/common/obj/PACKAGING/checkpublicapi-last-timestamp' failed
make: **\* [/home/moonlight/bliss/out/target/common/obj/PACKAGING/checkpublicapi-last-timestamp] Error 38
make: **\*   ....
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:1793: error 5: Added public field android.R.id.monitor_box
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:1802: error 5: Added public field android.R.id.seek_bar
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:1875: error 5: Added public field android.R.layout.slider_preference
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:1911: error 5: Added public field android.R.string.default_string
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:1914: error 17: Field android.R.string.fingerprint_icon_content_description has changed value from 17039384 to 17039385
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:11213: error 5: Added public field android.gesture.GestureOverlayView.mClearPerformedGesture
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:26048: error 3: Added class SlimSeekBarPreference to package android.preference
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:28749: error 5: Added public field android.provider.Settings.System.CUSTOM_CARRIER_LABEL
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:28763: error 5: Added public field android.provider.Settings.System.HIDE_LOCKSCREEN_DATE
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:28776: error 5: Added public field android.provider.Settings.System.NFC_POLLING_MODE
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:28798: error 5: Added public field android.provider.Settings.System.STATUS_BAR_CARRIER_FONT_SIZE
/home/moonlight/bliss/out/target/common/obj/PACKAGING/system-api.txt:34950: error 4: Added public method android.text.format.DateUtils.getAMPMCNString(int,int)

---

You have tried to change the API from what has been previously approved.

To make these errors go away, you have two choices:
   1) You can add "@hide" javadoc comments to the methods, etc. listed in the
      errors above.

   2) You can update current.txt by executing the following command:
         make update-api
# 

make update-api some more errors exist!

**Comment by moonlightly** [comment]
make update-api
after do this,more erros and prompt not have many files

**Comment by ericswpark** [comment]
@moonlightly , please try the latest version and report back. And please don't change any files during the build process.
